<?php

/**
 * sfMediaFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfMediaFileTable extends PluginsfMediaFileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfMediaFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfMediaFile');
    }
}