<?php

/**
 * sfMediaImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfMediaImageTable extends PluginsfMediaImageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfMediaImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfMediaImage');
    }
}