<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/27 11:11:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sfMediaPlugin',
  'username' => 'root',
  'password' => 123,
  'name' => 'doctrine',
)),);
