<?php

/**
 * sfMediaFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfMediaPlugin
 * @subpackage model
 * @author     Moujahid Mohamed
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfMediaFile extends BasesfMediaFile
{
}
