<?php

/**
 * sfMediaVideo
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sfMediaPlugin
 * @subpackage model
 * @author     Moujahid Mohamed
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfMediaVideo extends BasesfMediaVideo
{

  public function getInfosFromUrl($url)
  {
    $video = new sfVideo();
    return $this->getMediaObject($video->getVideoInfo($url));

  }

  public function getMediaObject($result)
  {
      $this->setCode($result["code"]);
      $this->setUrl($result["url"]);
      $this->setDescription($result["description"]);
      $this->setThumb($result["img"]);
      $this->setProvider($result["type"]);
      $this->setTitle($result["title"]);

      return $this;
  }
}
