<?php

/**
 * BasesfMediaFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type
 * @property string $code
 * @property string $title
 * @property string $url
 * @property string $thumb
 * @property string $description
 * @property string $provider
 * @property string $real_name
 * @property string $small
 * @property string $medium
 * @property string $large
 * 
 * @method string      getType()        Returns the current record's "type" value
 * @method string      getCode()        Returns the current record's "code" value
 * @method string      getTitle()       Returns the current record's "title" value
 * @method string      getUrl()         Returns the current record's "url" value
 * @method string      getThumb()       Returns the current record's "thumb" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method string      getProvider()    Returns the current record's "provider" value
 * @method string      getRealName()    Returns the current record's "real_name" value
 * @method string      getSmall()       Returns the current record's "small" value
 * @method string      getMedium()      Returns the current record's "medium" value
 * @method string      getLarge()       Returns the current record's "large" value
 * @method sfMediaFile setType()        Sets the current record's "type" value
 * @method sfMediaFile setCode()        Sets the current record's "code" value
 * @method sfMediaFile setTitle()       Sets the current record's "title" value
 * @method sfMediaFile setUrl()         Sets the current record's "url" value
 * @method sfMediaFile setThumb()       Sets the current record's "thumb" value
 * @method sfMediaFile setDescription() Sets the current record's "description" value
 * @method sfMediaFile setProvider()    Sets the current record's "provider" value
 * @method sfMediaFile setRealName()    Sets the current record's "real_name" value
 * @method sfMediaFile setSmall()       Sets the current record's "small" value
 * @method sfMediaFile setMedium()      Sets the current record's "medium" value
 * @method sfMediaFile setLarge()       Sets the current record's "large" value
 * 
 * @package    sfMediaPlugin
 * @subpackage model
 * @author     Moujahid Mohamed
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfMediaFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_media_file');
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('thumb', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('provider', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('real_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('small', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('medium', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('large', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->setSubClasses(array(
             'sfMediaVideo' => 
             array(
              'type' => 'video',
             ),
             'sfMediaImage' => 
             array(
              'type' => 'image',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}