<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/28 12:18:01
sfConfig::add(array(
  'app_sfMediaPlugin_small_size' => 50,
  'app_sfMediaPlugin_medium_size' => 100,
  'app_sfMediaPlugin_large_size' => 150,
  'app_sfMediaPlugin_directory' => array (
  'small_dir' => '/smallthumbs',
  'medium_dir' => '/mediumthumbs',
  'large_dir' => '/largethumbs',
),
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#FFFFFF',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
  'library' => 'gd_mime_type',
),
));
